version: "3"
services:
  node-sonos:
    container_name: air-node-sonos
    image: chrisns/docker-node-sonos-http-api
    network_mode: host
    volumes:
      - "./cache:/app/cache"
      - "./clips:/app/static/clips"
      - "./settings:/app/settings"
      - "./presets:/app/presets"
    restart: always
